### ISSUE TITLE
Missing dependency

### ISSUE THREAD

**Issue by agaldran** [IML-DKFZ/fd-shifts#1]
Hello,

Thanks for releasing your code. I am now trying to reproduce some of your results, and the first little problem I found after installing your library is that I tried to run `fd_shifts list` and got back this message:
```
ModuleNotFoundError: No module named 'pssh'
```
Apparently it can be fixed using `pip install parallel-ssh`, but I thought you may want to know and fix it.

Thanks!

**Comment by tbung** [comment]
Good catch, thank you very much! I've opted to move the import instead of adding it as a dependency, as it is currently only used to submit to remote machines, a functionality which currently only supports our own cluster anyway and is of no use to anyone without significant changes.
